#!/bin/bash -e

PASSWORD=admindax
USERNAME=admindax
mkdir /ftp
echo Setting credentials to $USERNAME:$PASSWORD
PASSWORD=$(perl -e 'print crypt($ARGV[0], "password")' $PASSWORD)
echo  useradd --shell /bin/sh --create-home --password $PASSWORD $USERNAME
useradd --shell /bin/sh --create-home --password $PASSWORD $USERNAME
chown -R $USERNAME:$USERNAME /ftp
exec proftpd --nodaemon